services:
  key-operations-portal-interface:
    build: key-operations-portal-interface
    ports:
      - "3000:3000"
    tty: true

  translational-informatics-access-management:
    build: translational-informatics-access-management
    ports:
      - "8000:8000"
    tty: true
    secrets:
      - db_password

  postgres:
    image: postgres
    build: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: /run/secret/db_password
    volumes:
      - ./data/postgres:/var/lib/postgresql/
    tty: true
    secrets:
      - db_password

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    volumes:
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

secrets:
  db_password:
    file: db_password.txt