services:
  key-operations-portal-interface:
    build: key-operations-portal-interface
    ports:
      - "8080:3000"
    tty: true

  translational-informatics-access-management:
    build: translational-informatics-access-management
    ports:
      - "8081:3000"
    tty: true
    secrets:
      - db_password

  postgres:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: /run/secret/db_password
    volumes:
      - ./data/translational-informatics-access-management-db:/var/lib/postgresql/
    tty: true
    secrets:
      - db_password

  postgres:
    image: postgres
    build: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: /run/secret/db_password
    volumes:
      - ./data/postgres:/var/lib/postgresql/
    tty: true
    secrets:
      - db_password

secrets:
  db_password:
    file: db_password.txt