apiVersion: v1
kind: Service
metadata:
  name: translational-informatics-access-management-load-balancer
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 3000
  type: LoadBalancer
  selector:
    app: translational-informatics-access-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translational-informatics-access-management
spec:
  selector:
    matchLabels:
      app: translational-informatics-access-management
  template:
    metadata:
      labels:
        app: translational-informatics-access-management
    spec:
      containers:
      - name: translational-informatics-access-management
        image: translational-informatics-access-management
        ports:
          - containerPort: 3000