apiVersion: v1
kind: Service
metadata:
  name: auth-db
  labels:
    app: auth-db
spec:
  clusterIP: None
  selector:
    app: auth-db
  ports:
  - port: 5432
    name: auth-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
spec:
  selector:
    matchLabels:
      app: auth-db
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - name: auth-db
        image: docker.io/library/postgres:16-alpine
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: authentik
          - name: POSTGRES_USER
            value: authentik
          - name: POSTGRES_PASSWORD_FILE
            value: /run/secrets/db_password
        volumeMounts:
          - name: auth-db-storage
            mountPath: /var/lib/postgresql/
          - name: auth-db-password
            readOnly: true
            mountPath: /run/secrets/db_password
            subPath: db_password
      volumes:
      - name: auth-db-password
        secret:
          secretName: auth-db-password
  volumeClaimTemplates:
    - metadata:
        name: auth-db-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-certs-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-templates-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  ports:
  - port: 9000
    name: http
    targetPort: 9000
  - port: 9443
    name: https
    targetPort: 9443
  type: LoadBalancer
  selector:
    app: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: authentik/server:2026.2
        securityContext:
          runAsUser: 1000
        command: ["dumb-init", "--", "ak", "server"]
        ports:
          - containerPort: 9000
          - containerPort: 9443
        env:
          - name: POSTGRES_DB
            value: authentik
          - name: POSTGRES_USER
            value: authentik
          - name: POSTGRES_PASSWORD_FILE
            value: /run/secrets/db_password
          - name: AUTHENTIK_POSTGRESQL__HOST
            value: auth-db
          - name: AUTHENTIK_POSTGRESQL__NAME
            value: authentik
          - name: AUTHENTIK_POSTGRESQL__PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-db-password
                key: db_password
          - name: AUTHENTIK_POSTGRESQL__USER
            value: authentik
          - name: AUTHENTIK_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: auth-secret-key
                key: secret_key
        volumeMounts:
          - name: auth-data
            mountPath: /data
          - name: auth-templates
            mountPath: /templates
      volumes:
        - name: auth-data
          persistentVolumeClaim:
            claimName: auth-data-claim
        - name: auth-templates
          persistentVolumeClaim:
            claimName: auth-templates-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-worker
spec:
  selector:
    matchLabels:
      app: auth-worker
  template:
    metadata:
      labels:
        app: auth-worker
    spec:
      containers:
      - name: auth-worker
        image: authentik/server:2026.2
        securityContext:
          runAsUser: 0
        command: ["dumb-init", "--", "ak", "worker"]
        env:
          - name: POSTGRES_DB
            value: authentik
          - name: POSTGRES_USER
            value: authentik
          - name: POSTGRES_PASSWORD_FILE
            value: /run/secrets/db_password
          - name: AUTHENTIK_POSTGRESQL__HOST
            value: auth-db
          - name: AUTHENTIK_POSTGRESQL__NAME
            value: authentik
          - name: AUTHENTIK_POSTGRESQL__PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-db-password
                key: db_password
          - name: AUTHENTIK_POSTGRESQL__USER
            value: authentik
          - name: AUTHENTIK_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: auth-secret-key
                key: secret_key
        volumeMounts:
          - name: auth-data
            mountPath: /data
          - name: auth-certs
            mountPath: /certs
          - name: auth-templates
            mountPath: /templates
      volumes:
        - name: auth-data
          persistentVolumeClaim:
            claimName: auth-data-claim
        - name: auth-certs
          persistentVolumeClaim:
            claimName: auth-certs-claim
        - name: auth-templates
          persistentVolumeClaim:
            claimName: auth-templates-claim