apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  ports:
  - port: 4566
    name: http
    targetPort: 4566
  type: LoadBalancer
  selector:
    app: localstack
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: localstack
spec:
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack
        ports:
          - containerPort: 4566
        volumeMounts:
          - name: localstack-storage
            mountPath: /var/lib/localstack
  volumeClaimTemplates:
    - metadata:
        name: localstack-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi