apiVersion: v1
kind: Service
metadata:
  name: key-operations-portal-interface
spec:
  ports:
  - port: 3000
    name: http
  type: LoadBalancer
  selector:
    app: key-operations-portal-interface
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-operations-portal-interface
spec:
  selector:
    matchLabels:
      app: key-operations-portal-interface
  template:
    metadata:
      labels:
        app: key-operations-portal-interface
    spec:
      containers:
      - name: key-operations-portal-interface
        image: key-operations-portal-interface
        ports:
          - containerPort: 3000