apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:18-alpine
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD_FILE
            value: /run/secrets/db_password
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/
          - name: db-password
            readOnly: true
            mountPath: /run/secrets/db_password
            subPath: db_password
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-volume-claim
      - name: db-password
        secret:
          secretName: db-password
