apiVersion: v1
kind: Service
metadata:
  name: structured-db
  labels:
    app: structured-db
spec:
  clusterIP: None
  selector:
    app: structured-db
  ports:
  - port: 5432
    name: structured-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: structured-db
spec:
  selector:
    matchLabels:
      app: structured-db
  replicas: 1
  template:
    metadata:
      labels:
        app: structured-db
    spec:
      containers:
      - name: structured-db
        image: structured-db
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD_FILE
            value: /run/secrets/db_password
        volumeMounts:
          - name: structured-db-storage
            mountPath: /var/lib/postgresql/
          - name: structured-db-password
            readOnly: true
            mountPath: /run/secrets/db_password
            subPath: db_password
      volumes:
      - name: structured-db-password
        secret:
          secretName: structured-db-password
  volumeClaimTemplates:
    - metadata:
        name: structured-db-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
