apiVersion: v1
kind: Service
metadata:
  name: translational-informatics-access-management-load-balancer
spec:
  ports:
  - port: 8000
    name: http
    targetPort: 8000
  type: LoadBalancer
  selector:
    app: translational-informatics-access-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translational-informatics-access-management
spec:
  selector:
    matchLabels:
      app: translational-informatics-access-management
  template:
    metadata:
      labels:
        app: translational-informatics-access-management
    spec:
      containers:
      - name: translational-informatics-access-management
        image: translational-informatics-access-management
        env:
          - name: LOCALSTACK_ENDPOINT
            value: "http://localstack:4566"
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
        ports:
          - containerPort: 8000